### ISSUE TITLE
Don't assume notifications will always be in the topic prefix

### ISSUE THREAD

**Issue by mtwomey** [topcoder-platform/tc-bus-api#1]
1. The topic prefix (KAFKA_TOPIC_PREFIX) should work when undefined (e.g. if there is no prefix, the application should still work)

1. "notifications" should not be assumed to be the prefix (guessing we'll have to update Connect here, because it's probably relying on that). Probably tc-bus-api doens't need to be updated regarding this notificaitons prefix, but Connect probably does.
![image](https://user-images.githubusercontent.com/7715262/34317819-9c3bd88e-e77c-11e7-96e9-e2fc40b39fc8.png)

**Comment by gondzo** [comment]
1. ok
2. 'notifications' prefix is in fact added by the event bus - that's just a way for us to keep track of topics in kafka that are related to notifications - there is no other specific use for it

**Comment by sachin-maheshwari** [comment]
Issue has been addressed in  PR - https://github.com/topcoder-platform/tc-bus-api/pull/6
