### ISSUE TITLE
Bus API not raising the event to the Kafka

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-bus-api#31]
There might be a possible issue with bus api where it is failing to send the event to the Kafka server while return 204 to the caller. I am seeing such instances multiple times since today morning. `projects-api` is calling bus api to send events to kafka bus and getting 204 in return but for the some weird reason, the event is not registered with kafka. I can not see the event in lauscher and none of the event consumers (legacy-project-processor and project-processor-es) is receiving the event.
Following is the log I am seeing in bus-api logs:
```
10:27:12 {"message":"ENTER postEvent","level":"debug"}
10:27:12 {"message":"input arguments","level":"debug"}
10:27:12 {"message":"{ event: \n { topic: 'project.action.create',\n originator: 'project-api',\n timestamp: '2020-02-12T04:57:12.652Z',\n 'mime-type': 'application/json',\n payload: \n { resource: 'project',\n createdAt: '2020-02-12T04:57:12.625Z',\n updatedAt: '2020-02-12T04:57:12.626Z',\n terms: [],\n id: 1xxxxx,\n name: 'Test'...
10:27:14 {"message":"ENTER postEvent","level":"debug"}
10:27:14 {"message":"input arguments","level":"debug"}
10:27:14 {"message":"{ event: \n { topic: 'connect.notification.email.project.notifications.generic',\n originator: 'tc-notifications',\n timestamp: '2020-02-12T04:57:14.547Z',\n 'mime-type': 'application/json',\n payload: \n { data: [Object],\n recipients: [Array],\n version: 'v3',\n from: [Object],\n categories: [Array] } } }","level":"debug"}
10:27:14 {"message":"EXIT postEvent","level":"debug"}
10:27:14 {"message":"output arguments","level":"debug"}
10:27:14 {"message":"undefined","level":"debug"}
```

Logging might be false alarm and just be issue of async nature but I am seeing correct sequence of Enter-Exit for all other requests other than the missing events.

**Comment by sachin-maheshwari** [comment]
As per sumologic alert, tc-bus logged following error - 
_{"timestamp":1581508113160,"message":{"name":"KafkaError","code":"NotLeaderForPartition","message":"This error is thrown if the client attempts to send messages to a replica that is not the leader for some partition. It indicates that the clients metadata is out of date."},"logStream":"PROD/tc-bus-api-container/327e9c3a-7575-44e0-9323-d8bf17955c0a","logGroup":"/aws/ecs/tc-bus-api"}
Host: /aws/ecs/tc-bus-api  
Name: PROD/tc-bus-api-container/327e9c3a-7575-44e0-9323-d8bf17955c0a  
Category: cloudwatch
loggroup: /aws/ecs/tc-bus-api  
logstream: PROD/tc-bus-api-container/327e9c3a-7575-44e0-9323-d8bf17955c0a  
test01: {"code":"NotLeaderForPartition","name":"KafkaError","message":"This error is thrown if the client attempts to send messages to a replica that is not the leader for some partition. It indicates that the clients metadata is out of date."}  
timestamp: 1581508113160_  
For the time being, i just recreated topic at  Cloudkarfka end and restarted the tc-bus service. It is working fine till now. So closing this issue for now.
